#!/usr/bin/python3
"""
This module provides a function to factorize a number into its prime factors.
"""

import sys


def factorize(n):
    """
    Factorize a number into its prime factors.

    :param n: The number to factorize.
    :type n: int
    :return: A tuple containing the prime factors of n.
    :rtype: tuple
    """
    for i in range(2, n):
        if n % i == 0:
            return (i, n // i)
    return None


if __name__ == '__main__':
    """
    This script reads numbers from a file and prints their prime factors.
    """
    if len(sys.argv) != 2:
        print('Usage: factors <file>')
        sys.exit(1)

    with open(sys.argv[1], 'r') as f:
        for line in f:
            n = int(line.strip())
            factors = factorize(n)
            if factors is not None:
                print(f'{n}={factors[1]}*{factors[0]}')
