#!/usr/bin/python3
"""
This module provides functions to check if a number is
prime and to factorize a number into its prime factors.
"""

import sys
from math import isqrt


def is_prime(n):
    """
    Check if a number is prime.

    :param n: The number to check.
    :type n: int
    :return: True if n is prime, False otherwise.
    :rtype: bool
    """
    if n <= 1:
        return False
    for i in range(2, isqrt(n) + 1):
        if n % i == 0:
            return False
    return True


def factorize(n):
    """
    Factorize a number into its prime factors.

    :param n: The number to factorize.
    :type n: int
    :return: A tuple containing the prime factors of n.
    :rtype: tuple
    """
    for i in range(2, isqrt(n) + 1):
        if n % i == 0 and is_prime(i) and is_prime(n // i):
            return (i, n // i)
    return None


if __name__ == '__main__':
    """
    This script reads a number from a file and prints its
    prime factors.
    """
    if len(sys.argv) != 2:
        print('Usage: rsa <file>')
        sys.exit(1)

    with open(sys.argv[1], 'r') as f:
        n = int(f.read().strip())
        factors = factorize(n)
        if factors is not None:
            print(f'{n}={factors[1]}*{factors[0]}')
